all:
  hosts:
    cp0:
      ansible_host: 51.250.11.99
      ansible_user: ubuntu
    node0:
      ansible_host: 51.250.94.124
      ansible_user: ubuntu
    node1:
      ansible_host: 51.250.110.23
      ansible_user: ubuntu
    node2:
      ansible_host: 51.250.37.179
      ansible_user: ubuntu
    node3:
      ansible_host: 51.250.94.120
      ansible_user: ubuntu
    node4:
      ansible_host: 51.250.110.42
      ansible_user: ubuntu
    node5:
      ansible_host: 51.250.37.16
      ansible_user: ubuntu
  children:
    kube_control_plane:
      hosts:
        cp0:
    kube_node:
      hosts:
        node0:
        node1:
        node2:
        node3:
        node4:
        node5:
    etcd:
      hosts:
        cp0:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
