all:
  hosts:
    cp1:
      ansible_host: 62.84.127.174
      ansible_user: ubuntu
    node1:
      ansible_host: 51.250.82.156
      ansible_user: ubuntu
    node2:
      ansible_host: 84.201.136.184
      ansible_user: ubuntu
    node3:
      ansible_host: 51.250.47.217
      ansible_user: ubuntu
  children:
    kube_control_plane:
      hosts:
        cp1:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        cp1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
